# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Q14/PrivateSpecs.git'
#source 'git@github.com:Q14/PrivateSpecs.git'

target 'MainProjectDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MainProjectDemo
  #pod 'QJRouter' , :path => '../../QJRouter'

	pod 'QJRouter',  '0.0.6'
  target 'MainProjectDemoTests' do
    inherit! :search_paths

	
    # Pods for testing
  end

  target 'MainProjectDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
